### ISSUE TITLE
Errors and UI Break on Clicking Settings

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2308] opened 2023-10-06 06:56 UTC
**Describe the bug**
Clicking on certain settings options triggers errors and leads to a complete UI break.

From @SorsOps after reading the user's crash reports from their session ID:

> - The issue seems to be caused by the use of spread on properties in React.
> - There is a React hook that is being broken and called conditionally, contributing to the problem.

**Not easily reproduced**
1. Navigate to the Settings page
2. Click on certain settings options

**Expected behavior**
The settings should open without any errors, and the UI should remain functional.

**Comment by six7** [comment] 2023-10-09 08:37
@keeganedwin can you add more reproduction steps? Not able to reproduce.

**Comment by keeganedwin** [comment] 2023-10-09 08:44
@six7 yea it's tough, even the user wasn't sure what he exactly clicked on that caused this... I don't know if @SorsOps has more information with the crash reports.

**Comment by esthercheran** [comment] 2023-10-10 06:20
@keeganedwin can you add the session id of the user?

**Comment by keeganedwin** [comment] 2023-10-10 06:24
@esthercheran ID: 5094827d9457499aab8e2b1ea60357bd

**Comment by keeganedwin** [comment] 2023-10-13 12:38
Another similar one: 2486ca8852bb4e9d91e8c7414237e94b

**Comment by esthercheran** [comment] 2023-10-13 13:29
@SorsOps can you add more details on what you found?

**Comment by SorsOps** [comment] 2023-10-20 06:42
Looks like the recording got lost off of sentry, but I took a look at the new one. I can't see the exact trigger, but I did look through all the UI components around the Token Listing. Nothing jumped out at me as a conditional react hook, unless one of the hooks uses another hook internally conditionally

**Comment by SamIam4Hyma** [comment] 2024-03-20 17:26
@keeganedwin another one to check on pretty please!

**Comment by SamIam4Hyma** [comment] 2024-04-09 16:43
@LukeFinch proposing we archive as its stale and the convo has gone cold. if you agree please close, if you think it needs ot be fixed please add the right label (bug) and remove archive.

**Comment by SamIam4Hyma** [comment] 2024-05-08 13:23
closing as it can't be reproduced

**Closed by SamIam4Hyma** 2024-05-08 13:23 UTC
Labels: bug, ☠️ Archive, settings - plugin page
