### ISSUE TITLE
Ability to just unlink the tokens without removem the layer properties.

### ISSUE THREAD

**Issue by isaquepereira** [tokens-studio/figma-plugin#2524] opened 2024-03-01 18:02 UTC
**Is your feature request related to a problem? Please describe.**
It's pretty annoying while duplicating and creating stuff that already linked to a token and when you update the tokens, those new elements are updated too.

**Describe the solution you'd like**
Would be nice have the ability to unlink tokens and keep the properties, because when I set to none or remove tokens it take alway every single property (color, stroke, etc).

**Describe alternatives you've considered**
None.

**Comment by keeganedwin** [comment] 2024-04-08 07:19
@six7 @esthercheran this seems to be a duplicate of #2378.

**Comment by LukeFinch** [comment] 2024-04-12 16:23
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Closed by LukeFinch** 2024-04-12 16:23 UTC
Labels: 💡request, token remove, UX user flow, 🩵 Migrated to Featurebase

**Comment by UdayHyma** [comment] 2024-04-15 09:12
Added to Featurebase Roadmap : [💡Removing a token removes the design property in figma](https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma)
