### ISSUE TITLE
Ability to  'Hide from publishing'  a single token

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2193] opened 2023-08-28 11:16 UTC
**Is your feature request related to a problem? Please describe.**
In Figma, there is a feature that allows users to hide variables from publishing. However, when syncing and creating variables within Tokens Studio, the 'Hide from publishing' checkbox gets reset.

**Describe the solution you'd like**
A feature enhancement in Tokens Studio that allows for preserving the 'Hide from publishing' setting. This enhancement would greatly reduce the number of component variables that do not need to be published or visible to other designers.

------

This is somewhat tied to the work in #2194 - and could possibly be done in parallel,

```[tasklist]
### Related
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2194
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2186
```

**Comment by LukeFinch** [comment] 2023-09-06 13:05
Is this a duplicate of #2186 ? Or is intended behaviour for if a user imports/syncs variables into the plugin?

**Comment by six7** [comment] 2023-09-06 16:23
this one is for the individual token, the other one for whole theme groups (collections)

**Comment by LukeFinch** [comment] 2023-09-11 06:44
Worth considering with this:
Whilst it's possible to hide a **style** from publishing - it's not possible to do this through the API (has to be done manually by a user in the assets panel). 

This and #2186 are very much **variable** specific. And should likely be directly tied in with the work for #2194

**Comment by six7** [comment] 2023-09-12 08:02
> Whilst it's possible to hide a style from publishing - it's not possible to do this through the API (has to be done manually by a user in the assets panel).

technically a user could name a style beginning with a `_` so it's hidden - but it's a bit of a hacky workaround i feel.

agree that the work around this should just be tied to Variables 👍

**Comment by esthercheran** [comment] 2023-10-18 07:17
Closing this ticket as this is covered in #2300

**Closed by esthercheran** 2023-10-18 07:17 UTC
Labels: design, variables-m2
