### ISSUE TITLE
Gitlab users are unable to create new branches

### ISSUE THREAD

**Issue by RYamashita3** [tokens-studio/figma-plugin#1760] opened 2023-03-27 17:59 UTC
**Describe the bug**
The connection to Gitlab is working, and I can create/edit tokens, push, pull, etc., but I'm unable to create new branches. Interestingly, prior to version 1.35.3, I was able to create new branches but not create/edit tokens or push to the repo. 

I have Maintainer access on the repo (direct access).

I've tried personal access tokens with all settings checked, and with just "api" checked. 

My access level on the parent Groups is "Guest".

**To Reproduce**
1. Go to the list of branches
2. Click on 'Create new branch from"
3. Select any branch
4. Add any name
5. See error "There was an error connecting. Check your credentials." (Error code 400 in console).

**Expected behavior**
I should be able to add new branches from the plugin

**Screenshots or Screencasts**
Credential settings:
![image](https://user-images.githubusercontent.com/118766580/228026353-ebd3a5e2-9cb2-413f-8f73-e09d18733e12.png)

**Comment by six7** [comment] 2023-04-15 10:04
I can't reproduce. I tried with:
- user is `guest` on group
- user is `maintainer` on repository

was able to connect and create branches just fine. can you provide more details?

**Comment by RYamashita3** [comment] 2023-04-18 16:00
@six7 : I can't reproduce this now either, so it looks like the issue has resolved itself. I'll open a new ticket if it resurfaces.

**Comment by six7** [comment] 2023-04-19 21:43
Perfect, closing this one then. 👍

**Closed** 2023-04-19 21:44 UTC
Labels: needs more info
