### ISSUE TITLE
Multi-dimensional themes: using groups on branch X and no groups in branch Y gives conflicts

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1934] opened 2023-05-31 10:53 UTC
**Describe the bug**
Multi-dimensional themes: using groups on branch X and no groups in branch Y gives conflicts

**Note**
This behaviour also seems to occur for JSONBin sync provider. On fetching the tokens from remote, same behaviour applies. https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1685023285219269 

**To Reproduce**
1. Have a branch setup with themes 'ungrouped'
2. Connect to a different branch, create theme groups and activate a few
3. Push that to the syncing provider
4. Connect again to your first branch > the plugin asks to pull theme changes
5. Once that is done, you will still have 2 active themes, while there is no theme selected.

**Expected behavior**
The amount of selected themes in the ungrouped token set, should reflect properly in the branch.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/109062656/a735772a-af8f-4093-81b8-18f96fe983c1

Probably related to: #1938

**Comment by kbsmth** [comment] 2023-07-12 16:59
I am seeing a similar bug, when using local storage. Due to my organizations prevention on using a sync provider and not having a generic versioned storage solution configured, I've had to manually create, export, and import tokens between my 3 core files in order to achieve alignment between files. 

**To Reproduce**

1. File A - create a group for my Light and Dark theme.
2. File A - create various token sets, and then assign them to their respective themes under "Manage Themes"
3. File A - export tokens to multiple files - export.
4. Unzip token export from File A
5. File B - ungrouped themes exist.
6. File B - import unzipped folder.
7. File B - theme selector shows that there is an active theme, but it is not selected. 
8. File B - when trying to select and unselect my "Light" theme, the plugin will switch between "Light" being active when it is unselected, and when I select "Light" the plugin displays "2 active".

To remedy the incorrect display of the active themes, I need to unselect everything in the theme selector, then in my token set list, find one of the 'checked' items, and un-select it. This breaks the "completeness" of the theme being perceived as active, and resets something that causes the theme selection behave as normal.

**Comment by six7** [comment] 2023-09-28 07:02
Fixed in 1.38 🚢

**Closed by six7** 2023-09-28 07:02 UTC
Labels: bug
