### ISSUE TITLE
[next/beta]: ability to remove a theme from a group

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#1876] opened 2023-05-09 14:49 UTC
A theme cannot be removed from a group. Allow the user to remove a theme from a group. 

https://user-images.githubusercontent.com/66366384/237133366-f911492f-c1f7-4ad1-8bb2-7aa1b9305079.mov

**Comment by six7** [comment] 2023-05-09 21:03
Duplicate of https://github.com/tokens-studio/figma-plugin/issues/1866

**Closed** 2023-05-09 21:03 UTC
