### ISSUE TITLE
Referencing a border token doesn't work

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1661] opened 2023-03-03 11:50 UTC
**Describe the bug**
If you reference a Border token in another Border token, the token isn't working properly. The token is applied, but the border doesn't show.

The color doesn't parse properly.

**Comment by six7** [comment] 2023-03-04 16:11
Duplicate of https://github.com/tokens-studio/figma-plugin/issues/1575

**Closed** 2023-03-04 16:11 UTC
