### ISSUE TITLE
Composition. Moving\arranging values in a convenient order

### ISSUE THREAD

**Issue by as-smirnov** [tokens-studio/figma-plugin#1635] opened 2023-02-21 19:39 UTC
**Is your feature request related to a problem? Please describe.**
When I fill in properties\values in a composition, I may not remember the clear order of properties\values in other previously filled compositions. Therefore, I have to record the order of properties\values in order to follow the same logic of filling in compositions, and this is extra time.
When there is a single structure, then checking the properties\values in the composition becomes much easier and faster.

**Describe the solution you'd like**
Dragging elements, for example, as in the properties of components in Figma ([See screenshot](https://tokens-studio.slack.com/files/U046CAGC9B5/F04KMHL0NHY/image.png)).
_If you couldn't open the screenshot, then go to the post in Slack_

**Hacking**
I found a solution that helps now, but it requires a lot of unnecessary actions. ([Watch the video](https://tokens-studio.slack.com/files/U046CAGC9B5/F04LBB62AQY/component_library.mp4)).
_If you were unable to open the video, then go to the message in Slack_

**Additional context**
Post in Slack
https://tokens-studio.slack.com/archives/C02JAL48UDN/p1674131995963349

**Comment by six7** [comment] 2023-02-27 08:04
Duplicate of https://github.com/tokens-studio/figma-plugin/issues/1559

Closing this one, let's keep discussion going in the other issue

**Closed by six7** 2023-02-27 08:04 UTC
