### ISSUE TITLE
Dropdown references with token-set header section

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1770] opened 2023-03-30 08:10 UTC
**Describe the issue:**
When searching for reference tokens in a dropdown, users have to carefully scroll down the list to find the right reference

<img width="469" alt="Screenshot 2023-03-30 at 1 31 09 PM" src="https://user-images.githubusercontent.com/93133012/228770452-28c6884c-520e-433f-8ff9-03acd9e4d42f.png">

**Proposal 1:**
The token-sets have a header section categorising the token-set
<img width="469" alt="Screenshot 2023-03-30 at 1 30 58 PM" src="https://user-images.githubusercontent.com/93133012/228771767-a5fdee01-5868-46b4-a2b1-37c5fff754e9.png">

**Proposal 2:**
The token-sets have a letter header section categorising the token-set
<img width="469" alt="Screenshot 2023-03-30 at 1 30 49 PM" src="https://user-images.githubusercontent.com/93133012/228772140-402aa237-f81a-4c25-b625-61574b320304.png">

**Comment by six7** [comment] 2023-04-06 07:00
I feel this would add clutter to the UI that might not be needed 🤔  Given not everyone follows the same naming pattern

**Comment by SamIam4Hyma** [comment] 2024-03-20 22:37
@keeganedwin I'm going to close this one with my comment because I think if the problem is the reference/alias user experience needs improvement we should be looking in to the problem so we can properly address with a solution that covers the widest audience possible. If it shows back up in feature base once we migrate, we can dig this back up. (:

**Closed by SamIam4Hyma** 2024-03-20 22:37 UTC
Labels: request
