### ISSUE TITLE
Ability To Specify The Font-style Type/Property

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2453] opened 2024-01-08 14:45 UTC
**Is your feature request related to a problem? Please describe.**
Add support for Font-style property.

**Used-case** 
The user wants to use Italics but not as part of the font-weight type.

**Comment by six7** [comment] 2024-01-09 10:26
Duplicate of https://github.com/tokens-studio/figma-plugin/issues/1639

**Closed by six7** 2024-01-09 10:26 UTC
