### ISSUE TITLE
Color Tokens Turn White in Figma's Variables List When Updating via Plugin

### ISSUE THREAD

**Issue by Ahmad-Fahmi** [tokens-studio/figma-plugin#2433] opened 2023-12-17 10:20 UTC
**Describe the bug**
Color tokens function properly within the plugin, and they used to work outside of it as well. However, now whenever I attempt to update Figma's native variables through the plugin by clicking on "Create Variables," all color tokens in Figma's variables list turn to white (#FFFFFF). Consequently, all components become white. I've refrained from creating new tokens because I won't be able to connect or apply them due to this issue.

**To Reproduce**
1. Go to 'Styles&Variables'
2. Click on 'Create Variables'
3. Go to Figma's variables list and all is white

**Screenshots or Screencasts**
![1](https://github.com/tokens-studio/figma-plugin/assets/107346959/96baf3b7-f933-4fa7-b433-ed05d1d95114)
![2](https://github.com/tokens-studio/figma-plugin/assets/107346959/a0a6dff0-f8e8-4814-83c4-6be5ab86567c)
![3](https://github.com/tokens-studio/figma-plugin/assets/107346959/f2612aa4-0fe3-4b78-ac18-3be6979a7707)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
[tokens.json](https://github.com/tokens-studio/figma-plugin/files/13695682/tokens.json)

**Comment by esthercheran** [comment] 2023-12-21 07:09
Hi @Ahmad-Fahmi I am unable to reproduce you issue. If you are part of the Token Studio Slack workspace, could you message me?

**Comment by SamIam4Hyma** [comment] 2024-03-21 22:15
@esthercheran proposing to close this one if we can't reproduce it, if you agree please close.

**Closed** 2024-05-07 20:05 UTC
Labels: bug, Figma variables, ☠️ Archive, Figma export
