### ISSUE TITLE
Changing a Token's Reference Changes the Reference in Both Variable Modes 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2278] opened 2023-09-28 07:31 UTC
**Describe the bug**
When changing the reference of a token and syncing it to its corresponding variable in a mode, it also changes the reference in the mode with the same token defined. 

**To Reproduce**
1. Have two modes with same tokens defined
2. Change reference of token 
3. Sync change to variable

**Expected behavior**
The sync should only reflect the change in one and not both modes. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/89305de2-cd0e-4699-88a2-96aa1374d8ed

**Comment by six7** [comment] 2023-09-28 19:08
Changing to P2. It's a bug, but it's not a bug introduced with 1.38. I was able to reproduce also on 1.37.11

**Comment by six7** [comment] 2023-10-01 09:30
Summarizing the investigation I did on this:

- This happens when you `Edit` a single token. After submitting the edit, we try to update that single variable that is connected to that token, and we do pass in the value that this token holds. However, we do this in a way that updates all modes. 
- We likely should instead be doing a calculation of all variables that would be changed due to that change of token, and then only update those. E.g. if you have a token that is a reference to many others, it's likely that change could cause quite a few variables to be updated. We should update all of these using the right values instead of the current approach which "forces" the value to all modes.

**Comment by SamIam4Hyma** [comment] 2024-04-08 17:17
@six7 looks like this is related to a V2 issues that is closed. Should this ticket also be closed? #2416

**Comment by six7** [comment] 2024-05-20 12:49
Closing as no longer able to reproduce

**Closed by six7** 2024-05-20 12:49 UTC
Labels: bug, Figma variables, token value references alias, plugin v2
