### ISSUE TITLE
[token-transformer@0.0.32] box shadow transformation

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [tokens-studio/figma-plugin#1754] opened 2023-03-26 11:47 UTC
Hey there! it's me again, this time with something that seemingly is actually a bug.

in token-transformer 0.0.32 we are getting the following output for a set of border radii

```
"Form-Active": {
      "Outline": {
        "Focus": {
          "value": {
            "0": "[object Object]",
            "1": "[object Object]"
          },
          "type": "boxShadow"
        }
      }
    },
```

In token-transformer 0.0.31 and older, we are getting the following output, which is great.

```
    "Form-Active": {
      "Outline": {
        "Focus": {
          "value": [
            {
              "color": "#1B5EE4",
              "type": "innerShadow",
              "x": 0,
              "y": 0,
              "blur": 0,
              "spread": 2
            },
            {
              "color": "#1b5ee41a",
              "type": "dropShadow",
              "x": 0,
              "y": 0,
              "blur": 0,
              "spread": 4
            }
          ],
          "type": "boxShadow"
        }
      }
    },
```

I'm unable to provide the complete set of source files due to a confidentiality agreement, but here's a piece of it that is causing it. Let me know if you would like me to provide a full reproduction, I'll cut up our source files.

```
    "Form-Active": {
      "Outline": {
        "Focus": {
          "value": [
            {
              "color": "{Alias.Color.Outline.Focus.Inner}",
              "type": "innerShadow",
              "x": "0",
              "y": "0",
              "blur": "0",
              "spread": "2"
            },
            {
              "color": "{Alias.Color.Outline.Focus.Outer}",
              "type": "dropShadow",
              "x": "0",
              "y": "0",
              "blur": "0",
              "spread": "4"
            }
          ],
          "type": "boxShadow"
        }
      }
    },
 ```

Some extra context, I'm using the $themes.json solution that was suggested here:

https://github.com/tokens-studio/figma-plugin/issues/1743

Let me know if I can help out. 0.0.32 seems to be an [npm published version](https://www.npmjs.com/package/token-transformer
), but if I look at the source files it seems that the current [should be 0.0.31](https://github.com/tokens-studio/figma-plugin/blob/main/token-transformer/package.json
) 

in the meanwhile I've just locked the version to 0.0.31 through `npx token-transformer@0.0.31 src/themes --theme --themeOutputPath dist`.

**Comment by six7** [comment] 2023-03-26 13:34
Could you perhaps provide a codesandbox? That would make it really easy to test. It's odd because we do have shadows in our test suite, so this should lead to a failing test. 🤔

The current version was published from the `next` branch - we had to fix a bug and didn't want to wait for the next plugin release. Sorry about that confusion. Ideally we'll move to a monorepo soon so we'll have less situations like that.

**Comment by six7** [comment] 2023-04-15 09:59
Closing this, I cannot reproduce. Would love a reproducable codesandbox or so. here's an example that you can fork (which shows it's working): https://codesandbox.io/p/sandbox/cocky-shape-23p3ke

**Closed by six7** 2023-04-15 09:59 UTC

**Comment by nopitown** [comment] 2023-08-22 18:15
I'm having the same error with the last version.

**Comment by Leland** [comment] 2023-11-15 13:08
@six7 also see https://github.com/tokens-studio/figma-plugin/issues/1878, which is the same thing.
