### ISSUE TITLE
Calculated values are not respected in variables

### ISSUE THREAD

**Issue by netleader** [tokens-studio/figma-plugin#2059] opened 2023-07-12 08:37 UTC
When you have 2 or more theme groups and a value of one group references a value of another, but uses math on top of it, we fail to save the calculated value back to Variables.

To reproduce:
- Create two sets: Core, Semantic/Light
- Create two theme groups: Core with a theme Default and Semantic with a theme Light. Use the sets from above respectively (Core: Core active, Semantic: Semantic active, Core source)
- In the Set for Core, create a token called `spacing.base` with a value of `4`
- In the set for Semantic/Light, create a token called `spacing.math` with a value of `{spacing.base} * 2`

Expected: We create 2 variables:
  - `spacing/base` in the Core collection with a value of 4
  - `spacing/math` in the Semantic/Light collection with a value of `8`.
- Actual result: We only created the `spacing.base` variable

We seem to just not create a variable when it has references and math inside. This was done with a decision to just focus on pure references, but in some cases users are fine with the value being stripped down to a calculated value or a hex value.

Note: The same applies when you are doing some kind of color manipulation: When you have a base color in the core set of `#ff0000` and in the semantic set you have a color with `rgba({basecolor}, 0.5)` instead of showing a 50% opaque red, we create the variable with a `#ffffff` which is wrong.

Let's create variables with the resolved variables **unless they are pure references, then create it like we do today.**

<details><summary>Original issue description</summary>
<p>

**Describe the bug**
We use some simple calculated values to create certain spacing like: 

4 + 2 = 6
{spacing.100} + {spacing.50} = 6

the result within the token is 6 but the value of the created variable is 0 (zero).

**Expected behavior**
The calculated value should be also the value of the variable.

</p>
</details>

**Comment by six7** [comment] 2023-07-17 06:41
I'm not able to reproduce

<img width="960" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/78a97bc7-0b00-4aff-89a5-519ae0c1062e">

<img width="1000" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/f01985ec-737b-4fed-9e7b-f358b3c354a0">

Are you sure your sets are setup correctly?

**Comment by six7** [comment] 2023-07-26 19:00
Can you share how you were able to reproduce? I have just tested with an alias in a different set and I was not able to reproduce

**Comment by six7** [comment] 2023-07-30 17:51
ah, i see - thank you for that extra context! 🙏 

it seems we have an issue updating values when they contain math. in this case we'd expect that the variable would not use any reference but rather apply the final output value which is `6`.

**Comment by six7** [comment] 2023-09-28 07:02
Fixed in 1.38 🚢

**Closed by six7** 2023-09-28 07:02 UTC
Labels: variables
