### ISSUE TITLE
Export modal: Add option to "resolve values"

### ISSUE THREAD

**Issue by dkaga** [tokens-studio/figma-plugin#1535] opened 2023-01-10 23:48 UTC
**Is your feature request related to a problem? Please describe.**
In the export modal, there is currently only an option to export the json using reference strings for base tokens instead of the real value:

```
{
  "colors": {
      "primary": {
        "value": "#2196F3",
        "type": "color"
      },
   },
  "buttons": {
      "dark": {
        "value": "{colors.primary}",
        "type": "color"
      }
   }
}
```

**Describe the solution you'd like**
I'm opening this as a new issue to see if adding the same feature available in the token-transformer to the export modal is possible, since I'm consuming the tokens in multiple applications, and it would simplify this process.  Example of the parsed json from above:

```
{
  "colors": {
      "primary": {
        "value": "#2196F3",
        "type": "color"
      },
   },
  "buttons": {
      "dark": {
        "value": "#2196F3",
        "type": "color"
      }
   }
}
```

**Describe alternatives you've considered**
Using the token-transformer package to manually parse the json.

**Additional context**
This request has been made in the [past](https://github.com/tokens-studio/figma-plugin/issues/423), but the issue was resolved when the `--preserveRawValue` flag was added to token-transformer.

**Comment by six7** [comment] 2023-01-14 10:12
Closing this as a duplicate of https://github.com/tokens-studio/figma-plugin/issues/423

**Closed by six7** 2023-01-14 10:12 UTC
