### ISSUE TITLE
Individual Properties Should Override “All” Property In Spacing Tokens

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2381] opened 2023-11-20 13:56 UTC
**Is your feature request related to a problem? Please describe.**
This is also related to #2377. 
As shown in the screenshots if `All` is applied from the spacing token `M`, and then `Right` & `Left` are applied from token `S`, then as you see `All` from token `M` stays selected/applied 

 
**Describe the solution you'd like**
When applying individual spacing properties to a frame with the `All` property, it should override the token`All` as it is no longer valid.

**Additional context**
Token M
![image](https://github.com/tokens-studio/figma-plugin/assets/140593995/3c9d27bf-139d-4b59-80c0-d9d8d5fdb669)

Token S
![image (1)](https://github.com/tokens-studio/figma-plugin/assets/140593995/619f1212-f92e-41f7-a2c8-ed76a5781e5a)
![image (2)](https://github.com/tokens-studio/figma-plugin/assets/140593995/52a2888a-c67d-447e-b944-6310583bff94)

**Comment by keeganedwin** [comment] 2024-05-14 18:21
@six7 closing this ticket as it seems like a duplicate of the ticket mentioned in description #2377.

**Closed by keeganedwin** 2024-05-14 18:21 UTC
Labels: bug
