### ISSUE TITLE
Applying Border Token Does Not Apply The Width As Variable

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2479] opened 2024-01-25 12:24 UTC
**Describe the bug**
When the `Border` property variable is applied to a frame via the plugin, doesn’t reflect the variable value in Figma. instead, it shows plain value. 

**To Reproduce**
1. Navigate to the plugin and make sure themes are defined
2. Create a `border` token with `colour` and `border-width` tokens referencing it.
3. Apply the border width token to a frame and see the error.

**Expected behavior**
when the `Border` token variable is applied to a frame via the plugin, the border property should reflect as a variable value in Figma.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/0e141b7f-8198-4fea-aea6-0dd6b546b0e7

**Figma file (optional)**
[Test File
](https://www.figma.com/file/fQDcDXnA94uHnOtR6UrfHU/Untitled?type=design&node-id=0%3A1&mode=design&t=hULCfL6Z7jfVlfzY-1)

**Comment by keeganedwin** [comment] 2024-01-25 14:29
Closing this as it is a duplicate of #2414

**Closed by keeganedwin** 2024-01-25 14:29 UTC
