### ISSUE TITLE
Gradient as a token is not applied

### ISSUE THREAD

**Issue by surfinzap** [tokens-studio/figma-plugin#1149] opened 2022-08-11 13:28 UTC
**Describe the bug**
I have the following color token: linear-gradient(105deg, rgba($color.tint.0, 1) 20%,  rgba($color.tint.0, 0) 65%)
When I apply it, nothing happens.
![image](https://user-images.githubusercontent.com/1387798/184143522-205f73da-8002-4e4e-9a84-d7bf91748324.png)

Here's the message I get in console:
[www.figma.com-1660224422275.log](https://github.com/six7/figma-tokens/files/9309023/www.figma.com-1660224422275.log)

**Comment by rbosker** [comment] 2022-08-11 13:55
@surfinzap I tried to reproduce this, with the same formula you are using, only with my own color tokens and that seems to be working properly. Can you check if color.tint.0 is configured properly? You should also be able to see a preview of the gradient in the token.

**Comment by surfinzap** [comment] 2022-08-12 09:50
Yeah, the color is configured properly, I can see the preview and how the variables are evaluated. Only the gradient is not applied. Let me know if there is anything else I can provide to help you investigate the issue.
![image](https://user-images.githubusercontent.com/1387798/184329689-ffba541b-3415-404f-bf90-c5b98d73d5ae.png)

**Comment by rbosker** [comment] 2022-08-12 14:30
This problem was caused by an extra space in the value: 
Doesn't work: linear-gradient(105deg, rgba($color.tint.0, 1) 20%,  rgba($color.tint.0, 0) 65%)
Works: linear-gradient(105deg, rgba($color.tint.0, 1) 20%, rgba($color.tint.0, 0) 65%)

@six7 would this be something we could tackle with error handling or stripping out the extra spaces?

**Comment by six7** [comment] 2022-08-14 20:42
> This problem was caused by an extra space in the value: Doesn't work: linear-gradient(105deg, rgba($color.tint.0, 1) 20%, rgba($color.tint.0, 0) 65%) Works: linear-gradient(105deg, rgba($color.tint.0, 1) 20%, rgba($color.tint.0, 0) 65%)
> 
> @six7 would this be something we could tackle with error handling or stripping out the extra spaces?

those are the exact same gradients, can you paste again?

**Comment by surfinzap** [comment] 2022-08-15 06:09
@six7 let me paste it as a monospaced font to spot the difference:
```
⛔: linear-gradient(105deg, rgba($color.tint.0, 1) 20%,  rgba($color.tint.0, 0) 65%)
✅: linear-gradient(105deg, rgba($color.tint.0, 1) 20%, rgba($color.tint.0, 0) 65%)
```

**Comment by six7** [comment] 2023-03-26 12:45
I'll close this in favor of a more structured token input via #1199

**Closed by six7** 2023-03-26 12:45 UTC
