### ISSUE TITLE
Changing The Stroke's Placement of A Border Removes The Variable

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2373] opened 2023-11-15 14:35 UTC
**Describe the bug**
Applying a color token as the border-color and changing the placement of the border (stroke) via Figma's UI: inside, outside, center removes the applied variable. When you apply the border-color after this its placement is then set to whatever option was previously selected. This is not a Figma bug as when you apply a variable via figma first and then change the placement of the stroke it stays intact -  See recording.

**To Reproduce**
1. Create variables
2. Apply a color token as the border-color
3. Change placement via Figma's UI
5. Apply color token again
6. See change

**Expected behavior**
Retain the applied variable even after the placement of the border is changed via Figma's UI. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/f1648d93-fcff-472b-a048-aa91ac79c846

**Figma file (optional)**
[Test file](https://www.figma.com/file/iILzlIuGfHyeP8suzX9vPi/Untitled?type=design&node-id=2-106&mode=design&t=W6ijgbFHvAOZeiaR-4)

**Comment by SamIam4Hyma** [comment] 2024-03-21 20:43
I can confirm this issue also exists when you are working with tokens connected to styles and not just variables. I will add this as a known issue in the docs until we can get it fixed.

**Comment by SamIam4Hyma** [comment] 2024-04-13 17:36
Added to Featurebase Roadmap as a known issue potentially impacting beta testing performance-	[❖ 🚧 ❇️ Variables in stroke weight and opacity](https://tokensstudio.featurebase.app/p/variables-in-stroke-weight-and-opacity)

**Comment by six7** [comment] 2024-05-15 05:47
I can't reproduce this anymore in 2.0, closing.

**Closed by six7** 2024-05-15 05:47 UTC
Labels: bug, Figma variables, known issue, Figma styles, token type border, Figma border properties, plugin v2, ❇️ Featurebase Roadmap
