### ISSUE TITLE
Space calculate tokens are broken my multidimensional tokens variables

### ISSUE THREAD

**Issue by itenorior** [tokens-studio/figma-plugin#2439] opened 2023-12-26 13:25 UTC
Hi, 

i am managing a multidimensional sets theme and i have some tokens that are a calculations depending from different set tokens.

For example

brand-tokens has a set of token called button and it contains a token called button-border-width.

Another group of theme called spaces and sizes has another set called button that contains a token called button-space-padding-vertical. This token is a calculation with {core-space-2xl} - {button-border-width}.

When a move all to variables, this token is 0 instead of 11px.

**Comment by keeganedwin** [comment] 2024-01-04 07:08
Hey @itenorior, would you be able to share an export of your tokens? Could you then also point me to the set/s where I can find these tokens to inspect the issue

**Comment by six7** [comment] 2024-01-04 21:29
I assume the issue lies in the space that you have in your calculation. If you change this to 

```diff
- {core-space-2xl} - {button-border-width}
+ {core-space-2xl}-{button-border-width}
```

Closing, feel free to reopen if the issue persists!

**Comment by itenorior** [comment] 2024-01-05 10:16
Please reopen the issue because i dont have permission for this.... @six7 

i attach the tokens set to make the test. You can see in touch theme the tokens button-space-padding-default-vertical.

I applied your solution how you can see but it didnt work.
[bug_token_studio_calculate_padding.json](https://github.com/tokens-studio/figma-plugin/files/13840752/bug_token_studio_calculate_padding.json)

![image](https://github.com/tokens-studio/figma-plugin/assets/154896605/b57a10e2-976e-4cb6-a54d-b4a11aa15f86)

![image](https://github.com/tokens-studio/figma-plugin/assets/154896605/4c155129-f3bc-415f-9298-57fd08119988)

**Comment by six7** [comment] 2024-01-07 21:21
Reopening, thanks for providing that 🙏

Will check out if we can get a reproduction going

**Comment by itenorior** [comment] 2024-01-11 14:23
any advance with the issue? @six7 ?

**Comment by SamIam4Hyma** [comment] 2024-04-13 18:24
@itenorior Have you tested this recently? I just did a bunch of math testing and everything seems to be working, including with or without spaces between the items in the equation. 

Adding the archive label here which will close the issue, but ping me if if needs to be reopened. (:

**Comment by SamIam4Hyma** [comment] 2024-05-06 20:11
Can't reproduce, will reopen if needed

**Closed by SamIam4Hyma** 2024-05-06 20:11 UTC
Labels: Figma variables, ☠️ Archive, themes, Figma export, token value - math functions
