### ISSUE TITLE
Variable Transaction Tracking

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2314] opened 2023-10-09 12:48 UTC
**Describe the bug**
I faced this bug when trying to navigate to the `Detach` section where the plugin would freeze right before opening the `Detach` modal. I tried to reproduce it but this time with the session recording enabled and the bug was present. Crash report analysis from @SorsOps:

Unable to find a variable with a specific key prior to the detach action.
	•	The missing variable is causing a freeze.
	•	Observation of a long transaction record.
	•	Currently tracking update tokens, but not the detach action.
	•	The actual DOM transactions complete quickly.
	•	Lack of tracking for figma variable logic.
	•	Gradual increase in memory usage during the freeze.

**To Reproduce**
1. Go to 'Manage Themes'
2. Click on Arrow to 'Detach styles & variables'
3. Click on 'Detach styles & variables' tab
4. See error - plugin freezes and you can't click on anything for a couple of minutes

**Screenshots or Screencasts**
Observation of a long transaction record:
![image (17)](https://github.com/tokens-studio/figma-plugin/assets/93133012/2826cf1d-8671-4e99-9d1b-595e7639d862)

Gradual increase in memory usage during the freeze.
![image (18)](https://github.com/tokens-studio/figma-plugin/assets/93133012/f66216fb-1b81-4697-b1c6-d9c615294081)

**Comment by six7** [comment] 2024-05-03 10:59
Unable to reproduce, closing - let's find a reproducable example

**Closed by six7** 2024-05-03 10:59 UTC
Labels: bug, crash, token detach
