### ISSUE TITLE
[token-transformer] 0.0.30 Border Token is still getting [Object Object]

### ISSUE THREAD

**Issue by ilxsil** [tokens-studio/figma-plugin#1674] opened 2023-03-08 14:29 UTC
**Describe the bug**
--expandBorder should be added by https://github.com/tokens-studio/figma-plugin/issues/1550 , latest version 0.0.30, but our team is still getting [Object Object] when transforming border token

**To Reproduce**
This is one of the border token that we're trying to transform.
```
 "textfield-border-disable": {
      "value": {
        "color": "{textfield-border-color-disable}",
        "width": "1px",
        "style": "solid"
      },
      "type": "border"
    },
```

**Expected behavior**
--expandBorder=true should not transform [Object Object]

**Screenshots of the transformed tokens in SCSS**
<img width="321" alt="Screenshot 2023-03-08 at 9 27 57 AM" src="https://user-images.githubusercontent.com/120485318/223739290-6611ac26-cef8-4f1a-831b-0ea1c0ef2fbf.png">

**Comment by six7** [comment] 2023-03-12 21:55
I can't reproduce, works fine for me: https://codesandbox.io/p/sandbox/cocky-shape-23p3ke?welcome=true

Can you please share a codesandbox that shows the problem?

input: 

![Image](https://user-images.githubusercontent.com/4548309/224576007-26772586-d824-4691-9b54-ee36e0e74198.png)

output:

![Image](https://user-images.githubusercontent.com/4548309/224575975-7885d95d-01a5-4d6e-ad39-0c8ac61d6699.png)

**Comment by SamIam4Hyma** [comment] 2024-04-12 18:13
@jorenbroekema is this still an issue? If not please close

**Comment by jorenbroekema** [comment] 2024-04-15 11:40
We can close this as "use sd-transforms instead of token-transformer"

**Closed by jorenbroekema** 2024-04-15 11:40 UTC
Labels: needs more info, transform tokens
