### ISSUE TITLE
Referencing Gradient Tokens does not Export Correct Styles

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3181] opened 2024-10-17 11:08 UTC
**Describe the bug**
Currently the plugin does not export gradient styles when the token is referencing another gradient.

**To Reproduce**
1. Create a gradient token with referencing two base tokens
2. Create another token referencing the first gradient token
3. Export styles as color

**Expected behavior**
Referencing another gradient should just be exported as a style.

**Screenshots or Screencasts**
From the screenshot the token `Base.Gamepad.Sparks-Like` is referencing the two base tokens above. You can see (annotated in green) that this token is successfully created as a style. However the token `Light.Semantic.Accent.Sparks-Like-Gradient` (annotated in red) that is referencing `Base.Gamepad.Sparks-Like` is not successfully created as a token:

![CleanShot 2024-10-17 at 13 00 21@2x](https://github.com/user-attachments/assets/ac9208c1-f30a-4d3a-b9eb-4b15bc335253)

**Figma file (optional)**
[Test file](https://www.figma.com/design/FwkrFHRvJ7EVCO7YytJDm3/Untitled?node-id=1-18&t=TwDF7cqKoFJyvK0R-4)

**Comment by tinder-andrewwagenhals** [comment] 2024-10-23 23:44
Hey @keeganedwin! Do you happen to have any updates on this ticket or a timeline to expect for the bug to be resolved?

**Comment by six7** [comment] 2024-10-26 17:41
Closing as duplicate of https://github.com/tokens-studio/figma-plugin/issues/3150 which already is in production

**Closed by six7** 2024-10-26 17:41 UTC
Labels: bug, Figma styles, needs-responder
