### ISSUE TITLE
Keep losing Github sync

### ISSUE THREAD

**Issue by Arno-Sympower** [tokens-studio/figma-plugin#1819] opened 2023-04-19 13:01 UTC
**Describe the bug**
Maybe It's because of Figma / Token studio updates, but I've had several times now that I lost the link with Github. One time It was the PA token that I had to re-generate and setup again in Github. The latest one Is a complete reset all together starting with the default screen:
![image](https://user-images.githubusercontent.com/121290044/233082142-8dcb27e9-c4f1-405d-94f1-ade9dbb5cbf2.png)

**To Reproduce**
It loses connection with Github in 2 different ways. Probably after Figma / Token studio updates.  The token is still there, not expired and without any changes.
After creating a new PA token, entering It and activating It again, It suddenly showed 2 Gitlab entries instead of one. So apparently It still had some registry of the old one, or It was a different bug. When I removed one they both disappeared. So I did the whole PA token, entering and activating It again, this time with success. I just hope that It keeps working stable from now on. 

**Expected behavior**
That the link keeps working. Even after updates.

**Screenshots or Screencasts**
Enclosed above.

**Comment by keeganedwin** [comment] 2023-10-24 11:32
Hey @Arno-Sympower, have you faced this issue again since this ticket was submitted?

**Comment by Arno-Sympower** [comment] 2023-10-25 14:06
I don't use token studio anymore, so, no ;-) 
Not (just) for this reason, also because mapping the colours and using them across libraries just wasn't working properly together with MUI. With the new Figma variables my problems are resolved.

**Comment by keeganedwin** [comment] 2023-10-26 08:37
@esthercheran I think you can mark this as closed?

**Comment by esthercheran** [comment] 2023-11-03 10:40
Closing this issue as not able to reproduce

**Closed by esthercheran** 2023-11-03 10:40 UTC
Labels: bug
